[env:esp32c3]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32c3

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MSC_ON_BOOT=0

lib_deps =
    olikraus/U8g2
    winlinvip/SimpleDHT@^1.0.15
